fix: download speed
kkdai/youtube pull request #286
Opened 2023-04-25 23:52 UTC by Davincible

# Description

Fix the download speed. Get 300+ Mb/s now.

- Switched to Android client
- Added multi-processing downloads

Code is very rough, could use some cleanup. But works for my purposes. Feel free to push to this branch directly to clean up.

All tests pass.

## Issues to fix

#217 #282

2023-04-27 11:07 UTC, Davincible commented
@corny

2023-04-27 14:01 UTC, corny requested changes

2023-04-27 14:01 UTC, corny commented on utils.go
> +		fmt.Println("returning item")
please remove `fmt.Println` statements

2023-04-29 07:36 UTC, denis-kilchichakov commented
Can't wait this PR to be merged - low speed makes this library barely usable :/

2023-04-30 09:33 UTC, pytomtoto commented
nice job

2023-04-30 09:42 UTC, Forsigg commented
> Can't wait this PR to be merged - low speed makes this library barely usable :/

Yep, fully agree. I'm already use this fork in my pet project, works great. Download speed has increased greatly.
Thanks @Davincible for this fix!

2023-05-03 17:29 UTC, Davincible commented
@corny

2023-05-04 09:35 UTC, merged

2023-05-04 10:05 UTC, corny commented
Thanks a lot for you work! I've just released a new version.